openapi: 3.0.0
info:
  title: Restful-booker API
  version: 1.0.0
paths:
  /auth:
    post:
      summary: Создание токена
      operationId: createToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /booking:
    get:
      summary: Получение списка ID бронирований
      operationId: getBookingIds
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookingId'
    post:
      summary: Создание бронирования
      operationId: createBooking
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingResponse'

components:
  schemas:
    AuthRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    AuthResponse:
      type: object
      properties:
        token:
          type: string
    BookingId:
      type: object
      properties:
        bookingid:
          type: integer
    Booking:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        totalprice:
          type: integer
        depositpaid:
          type: boolean
        bookingdates:
          type: object
          properties:
            checkin:
              type: string
            checkout:
              type: string
    BookingResponse:
      type: object
      properties:
        bookingid:
          type: integer
        booking:
          $ref: '#/components/schemas/Booking'